### ISSUE TITLE
Support mixed-protocol (UDP/TCP) LBs for exposing Gateways

### ISSUE THREAD

**Issue by rg0now** [l7mp/stunner-gateway-operator#21]
Currently creating a Gateway with a TCP listener and a UDP listener will not be correctly exposed in an LB service since many cloud-providers do not support this (currently we expose the first listener, and then all the listeners with the same protocol as the first one). This is suboptimal since many use cases will want to a couple in a single Gateway a UDP TURN listeners plus a TCP/TLS:443 listener that can be used as a fallback, and this is currently blocked by the operator. [Support of mixed protocols in Services with type=LoadBalancer: KEP-1435](https://github.com/kubernetes/enhancements/issues/1435) goes GA in Kubernetes v1.26, but we do not expect general provider support for this in the near future.

**Plan:** Some [Gateway implementations](https://metallb.universe.tf/usage/#ip-address-sharing) allow users to add an annotation to each Gateway to control whether mixed-protocol LBs should be enforced for this Gateway. The idea is to adopt this solution.

Say, one could disable STUNner's blocking of mixed-protocol LBs for specific Gateways by adding an annotation `stunner.l7mp.io/enable-mixed-protocol-lb: true` to it:

```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: mixed-protocol-gateway
  annotations:
    stunner.l7mp.io/enable-mixed-protocol-lb: true
spec:
gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: UDP
    - name: udp-listener
      port: 3478
      protocol: TCP
```

**Implementation:** see [here](https://github.com/l7mp/stunner-gateway-operator/blob/f73354e1668553df158687624e4242d4e28f072b/internal/renderer/service_util.go#L312). PR must come with unit tests and an integration test plus docs [here](https://github.com/l7mp/stunner/blob/main/doc/GATEWAY.md#gateway).
