### ISSUE TITLE
Insufficient memory for config-watcher container

### ISSUE THREAD

**Issue by davidkornel** [l7mp/stunner-gateway-operator#38]
As it stays in the title the current memory request is not sufficient for the config-watcher container in case it is used.
On GKE it will be immediately killed with an OOMKilled error. Right now it is limited to 20M of memory which should be raised or made configurable.
https://github.com/l7mp/stunner-gateway-operator/blob/main/internal/config/dataplane.go#L36

**Comment by rg0now** [comment]
Thanks. TBH, this was deliberately set to a very low value, just used for testing. The idea was that the Helm chart would create the `default` Dataplane resource at installation time and that resource would override the default set in this template. That being said, I'm OK with setting this to a higher value that will at least not result an OOM kill. Any suggestions?

**Comment by davidkornel** [comment]
When installing the charts separately (stunner and stunner-gw-op) the default value for the config-watcher is the following:
```yaml
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

The limit might be high, however, the request is sufficient.
