### ISSUE TITLE
ERROR updater cannot update service ... Invalid value: \"null\": may not change once set"

### ISSUE THREAD

**Issue by ignatiusreza** [l7mp/stunner-gateway-operator#42]
Followup issue first raised in #19.

In AWS EKS, services created with `type: LoadBalancer` will have its `loadBalancerClass` set to `service.k8s.aws/nlb`. The added keys is immutable and must be provided when the operator tries to synchronize and update existing services.

Example of the created service:

```yml
apiVersion: v1
kind: Service
metadata:
  name: stunner-gateway
  namespace: stunner
  labels:
    stunner.l7mp.io/owned-by: stunner
    stunner.l7mp.io/related-gateway-name: stunner-gateway
    stunner.l7mp.io/related-gateway-namespace: stunner
  annotations:
    meta.helm.sh/release-name: stunner-chart
    meta.helm.sh/release-namespace: stunner
    stunner.l7mp.io/related-gateway-name: stunner/stunner-gateway
spec:
  ports:
    - name: udp-listener
      protocol: UDP
      port: 3478
      targetPort: 3478
      nodePort: 31753
    - name: tls-listener
      protocol: UDP
      port: 443
      targetPort: 443
      nodePort: 32394
  selector:
    app: stunner
    stunner.l7mp.io/related-gateway-name: stunner-gateway
    stunner.l7mp.io/related-gateway-namespace: stunner
  clusterIP: A.B.C.D # filtered out
  clusterIPs:
    - A.B.C.D # filtered out
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  loadBalancerClass: service.k8s.aws/nlb
  internalTrafficPolicy: Cluster
```

Stack Trace of errors:

> ERROR	updater	cannot update service	{"operation": "unchanged", "service": "{\"metadata\":{\"name\":\"stunner-gateway\",\"namespace\":\"stunner\",\"creationTimestamp\":null,\"labels\":{\"stunner.l7mp.io/owned-by\":\"stunner\",\"stunner.l7mp.io/related-gateway-name\":\"stunner-gateway\",\"stunner.l7mp.io/related-gateway-namespace\":\"stunner\"},\"annotations\":{\"kots.io/app-slug\":\"labforward\",\"meta.helm.sh/release-name\":\"stunner-chart\",\"meta.helm.sh/release-namespace\":\"stunner\",\"stunner.l7mp.io/related-gateway-name\":\"stunner/stunner-gateway\"},\"ownerReferences\":[{\"apiVersion\":\"gateway.networking.k8s.io/v1beta1\",\"kind\":\"Gateway\",\"name\":\"stunner-gateway\",\"uid\":\"0a2e959e-da0a-4aa6-97db-42bc7f065c52\"}]},\"spec\":{\"ports\":[{\"name\":\"udp-listener\",\"protocol\":\"UDP\",\"port\":3478,\"targetPort\":0},{\"name\":\"tls-listener\",\"protocol\":\"UDP\",\"port\":443,\"targetPort\":0}],\"selector\":{\"app\":\"stunner\",\"stunner.l7mp.io/related-gateway-name\":\"stunner-gateway\",\"stunner.l7mp.io/related-gateway-namespace\":\"stunner\"},\"type\":\"LoadBalancer\"},\"status\":{\"loadBalancer\":{}}}", "error": "cannot upsert service \"stunner/stunner-gateway\": Service \"stunner-gateway\" is invalid: spec.loadBalancerClass: Invalid value: \"null\": may not change once set"}
github.com/l7mp/stunner-gateway-operator/internal/updater.(*Updater).ProcessUpdate
> 	/workspace/internal/updater/updater.go:115
github.com/l7mp/stunner-gateway-operator/internal/updater.(*Updater).Start.func1
> 	/workspace/internal/updater/updater.go:62
